<?php 

class Ref
{
    const DOWNLOADS_STATUS_COMPLETED = 'DOWNLOADS_STATUS_COMPLETED';
    const DOWNLOADS_STATUS_CREATED = 'DOWNLOADS_STATUS_CREATED';
    const DOWNLOADS_STATUS_ERROR = 'DOWNLOADS_STATUS_ERROR';
    const DOWNLOADS_STATUS_INPROGRESS = 'DOWNLOADS_STATUS_INPROGRESS';
    const MEDIA_STATUS_NEW = 'MEDIA_STATUS_NEW';
    const MEDIA_STATUS_SCAN = 'MEDIA_STATUS_SCAN';
    const MEDIA_STATUS_STORED = 'MEDIA_STATUS_STORED';
    const MEDIA_TYPE_MOVIE = 'MEDIA_TYPE_MOVIE';
    const MEDIA_TYPE_TVSHOW = 'MEDIA_TYPE_TVSHOW';
}