<?php

class Ref
{
    const MEDIA_STATUS_NEW = 'MEDIA_STATUS_NEW';
    const MEDIA_STATUS_STORED = 'MEDIA_STATUS_STORED';
    const MEDIA_TYPE_MOVIE = 'MEDIA_TYPE_MOVIE';
    const MEDIA_TYPE_TVSHOW = 'MEDIA_TYPE_TVSHOW';
}