<?php 

use Illuminate\Database\Migrations\Migration;
use FrenchFrogs\Laravel\Database\Schema\Blueprint;
use FrenchFrogs\Laravel\Support\Facades\Schema;
use \App\Models\Db\Users\Interfaces;

/**
 *
 *
 * @source Generated by FrenchFrogs\App\Console\CodeMigrationCommand
 * @since May 31, 2017
 * @author cotcotquedec@gmail.com
 */
class CreateInterfaceDefaultZ7fLGj extends Migration
{
    public function up()
    {
       Interfaces::create( [
           'sid' => Interfaces::DEFAULT,
           'name' => 'Alliwant'
       ]);
    }
    
    
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
