<?php

use App\Models\Db\Users\Interfaces;
use App\Models\Db\Users\Navigations;
use Illuminate\Database\Migrations\Migration;

/**
 *
 *
 * @source Generated by FrenchFrogs\App\Console\CodeMigrationCommand
 * @since Jul 12, 2017
 * @author cotcotquedec@gmail.com
 */
class CreateNavigationDownloadUVrTJF extends Migration
{
    public function up()
    {
        Navigations::create([
            'sid' => 'download',
            'interface_sid' => Interfaces::DEFAULT,
            'permission_sid' => null,
            'parent_sid' => null,
            'name' => 'Download',
            'link' => route('task.index.get'),
            'is_active' => true,
        ]);
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
