<?php

use FrenchFrogs\Laravel\Database\Schema\Blueprint;
use FrenchFrogs\Laravel\Support\Facades\Schema;
use Illuminate\Database\Migrations\Migration;

/**
 * Table principale de la gestion des media
 *
 * @source Generated by FrenchFrogs\App\Console\CodeMigrationCommand
 * @since Jun 2, 2017
 * @author cotcotquedec@gmail.com
 */
class CreateTableMediaTjM795 extends Migration
{
    public function up()
    {
        Schema::create("medias", function (Blueprint $table) {
            $table->binaryUuid('uuid');
            $table->reference('status_rid');
            $table->reference('type_rid')->nullable();
            $table->string('name');
            $table->string('dirname');
            $table->string('realpath');
            $table->string('file_md5', 32);
            $table->json('search_info')->nullable();
            $table->json('data')->nullable();
            $table->timestamps();
        });
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
