<?php

use App\Models\Db\Users\Interfaces;
use App\Models\Db\Users\Navigations;
use Illuminate\Database\Migrations\Migration;

/**
 * Initialisation de la navigation
 *
 * @source Generated by FrenchFrogs\App\Console\CodeMigrationCommand
 * @since Jun 3, 2017
 * @author cotcotquedec@gmail.com
 */
class CreateNavigationWew60O extends Migration
{
    public function up()
    {

        Navigations::create([
            'sid' => 'tvshows',
            'interface_sid' => Interfaces::DEFAULT,
            'permission_sid' => null,
            'parent_sid' => null,
            'name' => 'Series',
            'link' => route('tvshows'),
            'is_active' => true,
        ]);

        Navigations::create([
            'sid' => 'files',
            'interface_sid' => Interfaces::DEFAULT,
            'permission_sid' => null,
            'parent_sid' => null,
            'name' => 'Fichiers',
            'link' => route('files'),
            'is_active' => true,
        ]);


    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
