<?php

use App\Models\Db\Users\Interfaces;
use App\Models\Db\Users\Navigations;
use Illuminate\Database\Migrations\Migration;

/**
 * Ajout d dl page movie
 *
 * @source Generated by FrenchFrogs\App\Console\CodeMigrationCommand
 * @since Jun 3, 2017
 * @author cotcotquedec@gmail.com
 */
class AddMovieNavigationJ1XTVg extends Migration
{
    public function up()
    {

        Navigations::create([
            'sid' => 'movies',
            'interface_sid' => Interfaces::DEFAULT,
            'permission_sid' => null,
            'parent_sid' => null,
            'name' => 'Films',
            'link' => route('movies'),
            'is_active' => true,
        ]);
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
